# Generated by Django 2.1.2 on 2018-10-11 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentchild',
            name='is_highlight',
            field=models.BooleanField(default=False),
        ),
    ]
