# Generated by Django 2.1.2 on 2018-10-10 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='parentchild',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_name', models.CharField(max_length=50)),
                ('parent_domain', models.CharField(max_length=50)),
                ('child_name', models.CharField(max_length=50)),
                ('child_EA_Number', models.CharField(max_length=50)),
                ('child_domain', models.CharField(max_length=50)),
            ],
        ),
    ]
